use sakila;

# 1
# List the number of films per category.
select count(film_id) as number_of_films, category_id 
from film
inner join film_category
using (film_id)
group by category_id
;

# Retrieve the store ID, city, and country for each store.
select store_id, city, country_id
from store
inner join address using (address_id)
inner join city using (city_id)
group by store_id
;

# Calculate the total revenue generated by each store in dollars.
select store_id, CONCAT('$', FORMAT(SUM(amount), 2)) as revenue_generated
from staff
inner join store using (store_id)
inner join payment using (staff_id)
group by store_id
;

# Determine the average running time of films for each category.
select category_id, lower(concat(floor(avg(length)/60), ' hours ', round(avg(length)%60, 0), ' minutes')) as avg_length
from film
inner join film_category using (film_id)
group by category_id;
;